# Generated by Django 5.0.1 on 2024-01-03 15:59

import embed_video.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('screenshots', models.ImageField(unique=True, upload_to='screenshots/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(unique=True, upload_to='images/')),
                ('trailer', embed_video.fields.EmbedVideoField()),
                ('developer', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('video_card', models.CharField(max_length=150)),
                ('disk_space', models.CharField(max_length=50)),
                ('file', models.FileField(unique=True, upload_to='files/')),
                ('about', models.TextField()),
                ('category', models.ManyToManyField(to='categories.category')),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('screenshots', models.ManyToManyField(to='games.screenshots')),
            ],
        ),
    ]
