# Generated by Django 5.0.3 on 2024-03-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='customer',
        ),
    ]
